### ISSUE TITLE
mobile should have an hamburger menu

### ISSUE THREAD

**Issue by nloureiro** [ethereum/cryptography-research-website#3]
![Screen Shot 2022-04-04 09 22 50 AM](https://user-images.githubusercontent.com/1120748/161529014-918134d2-d66b-4037-a198-94b3c98d3229.png)

**Comment by konopkja** [comment]
![menu](https://user-images.githubusercontent.com/100724231/161535142-bce3d9a4-87a8-473b-89bd-72f1a54bf504.png)
could look something like this, also as an external link bounties should be marked

**Comment by nhsz** [comment]
@nloureiro @konopkja let me know what you think https://deploy-preview-7--adorable-dragon-259617.netlify.app/

**Comment by konopkja** [comment]
Looks already pretty good! the only improvement i could think of is clickable are. sometimes it can be hard with big fingers to hit small areas :D 
<img width="336" alt="Screenshot 2022-04-06 at 19 43 06" src="https://user-images.githubusercontent.com/100724231/162001991-71e0bfdd-e416-439c-90bd-b3aac40059a8.png">
a

**Comment by nhsz** [comment]
@konopkja updated in the current site https://cryptography-research.netlify.app/
