### ISSUE TITLE
max width of the grid

### ISSUE THREAD

**Issue by nloureiro** [ethereum/cryptography-research-website#4]
the grid looks estrange when display on big screens, probably max-width of 1440 or less.

![Screen Shot 2022-04-04 09 23 11 AM](https://user-images.githubusercontent.com/1120748/161529171-105c8e79-e592-4f31-8aaf-9d0c7479b0c0.png)

**Comment by samajammin** [comment]
Yes I agree with this 😄 

I'm still seeing wide layout on large screens:
![Image 2022-04-06 at 12 11 52 PM](https://user-images.githubusercontent.com/8097623/162051032-3f5ae267-a600-4dd4-931f-6c673ee03a8d.jpg)

I think we should apply a max-width for the nav as well to contain all content. Similar to how https://medium.com/ approaches it:
![Image 2022-04-06 at 12 11 44 PM](https://user-images.githubusercontent.com/8097623/162051132-7e7602a5-3871-4816-b3fd-3db0bf6be647.jpg)

**Comment by nloureiro** [comment]
I would go to the LG breakpoint for the max-width of all content >>> 1024px

The simplicity of the theme and the content might be enough. Leaving a more significant margin for the main content.

![Screen Shot 2022-04-07 09 29 20 AM](https://user-images.githubusercontent.com/1120748/162155989-be4b5a79-3057-450b-a920-e895206c85df.png)
![Screen Shot 2022-04-07 09 25 55 AM](https://user-images.githubusercontent.com/1120748/162156006-19f1f810-4e4b-4c4a-a583-b81056d8221b.png)


with this, we might have fixed the different container max-width that was making the <main> jump a bit.

https://user-images.githubusercontent.com/1120748/162158221-505d33e0-2740-4bb9-893e-82f5fc379a26.mov

**Comment by nhsz** [comment]
fixed now
