### ISSUE TITLE
Update favicon?

### ISSUE THREAD

**Issue by samajammin** [ethereum/cryptography-research-website#9]
Noticed the favicon color is different from the primary logo:
![Image 2022-04-24 at 2 15 52 PM](https://user-images.githubusercontent.com/8097623/164976044-ebb51fe4-b0fb-484a-92d5-70f90d98cddd.jpg)

I suggest we update the favicon to match the rainbow glyph. @nhsz I think we could probably just grab the same one used on ethereum.foundation?
https://github.com/ethereum/ethereum-foundation-website/blob/master/src/images/favicon.png

**Comment by nhsz** [comment]
thx, updated now!
